//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEstimationTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectEstimationTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string CaptionUnsavedChanges {
            get {
                return ResourceManager.GetString("CaptionUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO DO: Project Description.
        /// </summary>
        public static string DefaultRootTaksDescription {
            get {
                return ResourceManager.GetString("DefaultRootTaksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value that is less than 1666.65 hours.
        /// </summary>
        public static string ErrorGreaterThanMaxHours {
            get {
                return ResourceManager.GetString("ErrorGreaterThanMaxHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value that is less than 99999 minutes.
        /// </summary>
        public static string ErrorGreaterThanMaxMinutes {
            get {
                return ResourceManager.GetString("ErrorGreaterThanMaxMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value that is greater than zero.
        /// </summary>
        public static string ErrorLessThanZero {
            get {
                return ResourceManager.GetString("ErrorLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be numeric.
        /// </summary>
        public static string ErrorNotNumeric {
            get {
                return ResourceManager.GetString("ErrorNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema version {0} is not supported by this version of the program.
        /// </summary>
        public static string ErrorUnsupportedSchemaVersion {
            get {
                return ResourceManager.GetString("ErrorUnsupportedSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaf item cannot have a child.
        /// </summary>
        public static string LeafTreeItemExceptionMessage {
            get {
                return ResourceManager.GetString("LeafTreeItemExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string MeasurementHoursLabel {
            get {
                return ResourceManager.GetString("MeasurementHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string MeasurementMinutesLabel {
            get {
                return ResourceManager.GetString("MeasurementMinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        public static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to the project have not been saved. Would you like to save these changes?.
        /// </summary>
        public static string QuestionSaveChanges {
            get {
                return ResourceManager.GetString("QuestionSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property can only be set on a leaf item.
        /// </summary>
        public static string SetBranchTreeItemPropertyExceptionMessage {
            get {
                return ResourceManager.GetString("SetBranchTreeItemPropertyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database last update date and time record is missing.
        /// </summary>
        public static string SQLiteDataAccess_DatabaseLastUpdateDateTimeNotFound {
            get {
                return ResourceManager.GetString("SQLiteDataAccess_DatabaseLastUpdateDateTimeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database schema version number not found.
        /// </summary>
        public static string SQLiteDataAccess_DatabaseSchemaVersionNotFound {
            get {
                return ResourceManager.GetString("SQLiteDataAccess_DatabaseSchemaVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the database file must be specified.
        /// </summary>
        public static string SQLiteDataAccess_EmptyFilePath {
            get {
                return ResourceManager.GetString("SQLiteDataAccess_EmptyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path.
        /// </summary>
        public static string SQLiteDataAccess_InvalidFilePath {
            get {
                return ResourceManager.GetString("SQLiteDataAccess_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project version number not found.
        /// </summary>
        public static string SQLiteDataAccess_ProjectVersionNotFound {
            get {
                return ResourceManager.GetString("SQLiteDataAccess_ProjectVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported schema version.
        /// </summary>
        public static string SQLiteDataAccess_UnsupportedDatabaseSchemaVersion {
            get {
                return ResourceManager.GetString("SQLiteDataAccess_UnsupportedDatabaseSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error.
        /// </summary>
        public static string UndefinedError {
            get {
                return ResourceManager.GetString("UndefinedError", resourceCulture);
            }
        }
    }
}
